### ISSUE TITLE
ERROR: inconsistent number of segments for chromosome 4

### ISSUE THREAD

**Issue by tamaraprieto** [raphael-group/CNTMD#2]
Hi, 

I am running your program in this way: 

`mixcnp input.samples -Z 120 -d -j 1 -k 3 -m 4000 -ni 5 -ns 5 -nt 1 -o result.out -s 120 -t 0.001 -ss 12 &> log
`
For the example file, I get the output and everything looks right. However, when I use the input generated from my data I get the following error:

> terminate called after throwing an instance of 'std::runtime_error'
>   what():  ERROR: inconsistent number of segments for chromosome 4

My input looks like this (I have generated it using your script):

#PARAMS
22 #number of chromosomes
2 #number of samples
1 1 3 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 #number of segments for each chromosome
#SAMPLES 1 : 784903,249201565 | 2 : 23368,242985695 | 3 : 61495,145420382 145489815,145498521 145499439,197846280 | 4 : 10834,190790246 | 5 : 851582,180781326 | 6 : 205696,170919735 | 7 : 99392,159122935 | 8 : 142425,146300287 | 9 : 204850,141058424 | 10 : 94426,135235890 | 11 : 197337,134946396 | 12 : 189093,133820866 | 13 : 19449788,114999838 | 14 : 20425051,107287663 | 15 : 20004669,102431166 | 16 : 83802,89998957 | 17 : 1869,79989546 | 18 : 125371,78014614 | 19 : 108032,59091717 | 20 : 20002137,62954871 | 21 : 15273817,48101335 | 22 : 16852667,22514133 22517026,22755065 23249354,49996056
0-CLL04.BM : 1.98 | 1.98 | 1.98 1.98 2.95 | 1.98 | 1.98 | 1.97 | 1.99 | 1.99 | 1.98 | 2.0 | 1.99 | 1.99 | 1.98 | 1.98 | 1.99 | 2.01 | 2.0 | 1.97 | 2.02 | 2.0 | 1.99 | 2.0 0.94 2.01
1-CLL04.PB : 2.0 | 1.99 | 1.99 3.0 3.0 | 2.0 | 2.0 | 1.99 | 2.0 | 2.0 | 2.0 | 2.01 | 2.0 | 2.0 | 1.99 | 1.99 | 2.0 | 2.03 | 2.02 | 1.99 | 2.04 | 2.01 | 2.0 | 2.02 0.94 2.02

I had also tried to tune the parameters according to my data but it seems an error related with the input format but it looks very similar to your example: 

#PARAMS
2 #number of chromosomes
2 #number of samples
2 3 #number of segments for each chromosome
#SAMPLES 1 : 10001,6000001 6000001,249225000 | 3 : 60001,129760000 129760001,129805000 129805001,197900000
0-CA_1 : 2.0 2.0 | 2.0 0.19 2.01
1-CA_2 : 2.01 2.0 | 2.0 2.0 2.0

I would be really grateful if you can help me figure out what is going on. 
Thanks
Tamara

**Comment by simozacca** [comment]
Dear Tamara, 

The input that gave the error does not look right indeed as the chromosomes appear to be shuffled in their size. As such we need some more information, more specifically:

1. Did you use `make_input.py` to generate this input?
2. Could you please provide you original input?

Thank you

**Comment by tamaraprieto** [comment]
1. Yes, I generated it using `make_input.py`
2. Of course, here you are
[Input.CNT-MD.txt](https://github.com/raphael-group/CNT-MD/files/2629855/Input.CNT-MD.txt)

I used the same command in the documentation
`python 
/mnt/lustre/scratch/home/uvi/be/tpf/APPS/CNT-MD/utils/make_input.py Input.CNT-MD.txt -c 2 -b 30 -m 12 -u 0.3 > input.samples
`
Thank you

**Comment by simozacca** [comment]
There was a bug in the script to generate the input that was shuffling the chromosome's sizes incorrectly.
Please pull the new version and also recompile the program.

I tested with your input both the script and the program, and everything looks good.
Please let me know if everything is working fine from your side, too

**Comment by tamaraprieto** [comment]
It works!thank you very much
