### ISSUE TITLE
CNT-MD throughs uncatched exception when run on A10-cleaned.samples

### ISSUE THREAD

**Issue by stardustcx** [raphael-group/CNTMD#4]
Dear Simone Zaccaria,
I recently reported this issue by email. According to your suggestion, I compiled the newest version of CNT-MD with a lemon library compiled without ILOG and SOPLEX. The boost library was 1.68 which cmake complained about newer than expect. The resulting mixcnp can deal with data/test/log2ratios.tsv (convert by utils/make_input.py), but cannot deal with data/real/gundem2015/A10-cleaned.samples (throughs uncatched exceptions). There was still no other log except for an exit code 7 and exception.
![image](https://user-images.githubusercontent.com/20909164/49338413-bee5fb00-f65b-11e8-9c57-1e30ec642f66.png)

In addition, my gcc.8.2 and g++8.2 compilers repeated warninigs as following:
![cnt-md compilewarnnings](https://user-images.githubusercontent.com/20909164/49338303-6b26e200-f65a-11e8-93b2-8d788bd0c5d9.jpg)
I'm not sure what's the problem. Can it be caused by boost lib (1.68) or CPLEX (version 128)? What's the suggested version of boost and CPLEX?
Thank you again for your rapid response and active maintenance.

**Comment by simozacca** [comment]
CNT-MD is not printing the exception because the exception is thrown by CPLEX. I added a specific CATCH to capture CPLEX exceptions and print the message.

Please pull the new version, recompile everything from scratch, and report the new log and errors so we can investigate the issue.

Thanks

**Comment by stardustcx** [comment]
I pulled and recompiled the latest version. It says "CPLEX Error  1016: Promotional version. Problem size limits exceeded." Should I buy the full CPLEX permission?

Thank you!

**Comment by simozacca** [comment]
The trial version of CPLEX limits the size of the model. However, IBM academic initiative offers a free license for the full version of CPLEX for any academic person, including students and faculty.

You can easily request an academic license [here](https://ibm.onthehub.com/WebStore/ProductSearchOfferingList.aspx?srch=ilog%20cplex) and you can read more details [here](https://www.ibm.com/products/ilog-cplex-optimization-studio)
